### ISSUE TITLE
The rp output is not Zsymetric

### ISSUE THREAD

**Issue by romaindegivry** [AlexMontgomerie/4NEC2_helical_gen#7]
@AlexMontgomerie Any idea why though?
My point is that if the antenna is pointn along the \vec{e}_z direction we should see the bulge in gain in that direction as well. 
Here's a picture of the output with a dot at z=10 (x,y=0,0)
![out](https://user-images.githubusercontent.com/16005829/29083632-48448ce8-7c61-11e7-81f9-abfc29dedba7.png)

**Comment by AlexMontgomerie** [comment]
i think it's cos we aren't driving properly. It's just getting driven by one side, so there are probably issues with that. Also, we need to make sure it follows nec rules for segment sizes and freq dependencies. I'll write a function to verify (or try find one in the source code) and add an extra excitation card for the other wire.
