### ISSUE TITLE
issue with reg expression

### ISSUE THREAD

**Issue by AlexMontgomerie** [AlexMontgomerie/4NEC2_helical_gen#9]
```
 match_number = re.compile('-?\ *[0-9]+\.?[0-9]*(?:[Ee]\ *-?\ *[0-9]+)?')
```
There's an issue with my table parsing method. It's having problems with the zeros in a line, not correctly putting them into a single zero. I'll take a look at the expression it's trying to match with.

**Comment by romaindegivry** [comment]
try this
`'(\d+)?\.?(\d+?( |([Ee][\+\-]?[\d]{0,3})))'`
it is tested on:
```
INPUT POWER   =  5.7653E-005 Watts
.7653 Watts
.0123E3 
0.000 
``` 
It still relies on a space after the number for fixed point cases though

**Comment by AlexMontgomerie** [comment]
```
'-?\ *[0-9]+\.?[0-9]*(?:[Ee]\ *[+\-]?\ *[0-9]+)?'
```
turns out i forgot to incorporate + for sci notation.
